### ISSUE TITLE
Scanner can not be installed via composer

### ISSUE THREAD

**Issue by valencia-komunikation** [ohader/scanner#13]
Currently it is not possible to install the package via composer.
When requiring typo3/cms-scanner as the composer name suggests, I get the error `- The requested package typo3/cms-scanner could not be found in any version, there may be a typo in the package name.` which is clear since the package is not available at packagist.

I tried adding the github url as repo in my composer.json like this:
```
"repositories": [
	{"type": "vcs", "url": "https://github.com/ohader/scanner"}
]
```
but I am still getting the same error.

What can I do to add the extension scanner to my project?

**Comment by DavidBruchmann** [comment]
As the repository never has a release you've to require `dev-master` or a specific branch or state.
```
    "require": {
        "typo3/cms-scanner": "dev-master"
    },
```

**Comment by DavidBruchmann** [comment]
Also keep in mind that scanner is seemingly only available for TYPO3 v9 but that won't affect your efforts to install it by composer.

**Comment by valencia-komunikation** [comment]
Thanks for the hint. Thought that
```
 "require": {
    "typo3/cms-scanner": "*"
},
```
would also include dev-master.

Closing.
